[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anki-vocab-miner-Crimxxxxn"
version = "1.0"
description = "Japanese word scanner to help with batch mining words for anki"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Crimxxxn" }
]

dependencies = [
    "sudachipy",
    "sudachidict-full",
    "requests"
]

[project.urls]
Repository = "https://github.com/Crimxxxxn/anki-vocab-miner"